version: '3.7'

networks:
  triptime:

services:
  spa:
    container_name: react-spa
    restart: always
    stdin_open: true
    volumes:
      - './src/spa-react:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    networks:
      - triptime
    depends_on:
      - php

  php:
    container_name: php
    volumes:
      - ./src/api:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - triptime
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: triptime
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - triptime
