version: '3'

networks:
  triptime:

services:
  spa:
    container_name: react-spa
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    build:
      context: ./src/spa
      dockerfile: Dockerfile
    depends_on:
      - api
    restart: always
    networks:
      - triptime

  api:
    image: nginx:stable-alpine
    container_name: api-laravel
    ports:
      - "8080:80"
    volumes:
      - ./src/api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - triptime

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: triptime
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - triptime

  php:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/api:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - triptime

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src/api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - triptime

  artisan:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    container_name: artisan
    volumes:
      - ./src/api:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - triptime