version: '3.7'

services:
  spa:
    build:
      context: ./src/spa-react
      dockerfile: Dockerfile

  php:
    build:
      args:
        user: container-user
        uid: 1000
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"