version: '3.7'

services:
  spa:
    container_name: nextjs-dev
    build:
      context: ./src/spa
      dockerfile: dev.Dockerfile
    environment:
      - APP_HOSTNAME=http://localhost:3000
      - API_HOSTNAME=http://localhost:8080
    ports:
      - "3000:3000"

  php:
    ports:
      - "8080:8080"
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8080"]