version: '3.7'

networks:
  triptime:

services:
  spa:
    restart: always
    stdin_open: true
    volumes:
      - './src/spa:/app'
      - '/app/node_modules'
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - CYPRESS_INSTALL_BINARY=0
      - PUSHER_APP_KEY=accecccf74f749839e36
      - PUSHER_APP_CLUSTER=ap4
      - PORT=3000
    networks:
      - triptime
    depends_on:
      - php

  php:
    container_name: php
    build:
      args:
        user: container-user
        uid: 1000
      context: ./src/api
      dockerfile: Dockerfile
    volumes:
      - ./src/api:/var/www/html
      - /var/www/html/vendor
    ports:
      - "9000:9000"
    networks:
      - triptime
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: triptime
      MYSQL_USER: app
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_PASSWORD: app_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - triptime
