version: '3.7'

services:
  spa:
    container_name: nextjs
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000"
    volumes:
      - /app/.next
    build:
      context: ./src/spa
      dockerfile: prod.Dockerfile
      args:
        APP_HOSTNAME: http://localhost
        API_HOSTNAME: http://localhost
        PUSHER_APP_KEY: accecccf74f749839e36
        PUSHER_APP_CLUSTER: ap4

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/api:/var/www/html
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf:ro
    networks:
      - triptime
    depends_on:
      - php
      - mysql
      - spa
