version: '3'

networks:
  triptime:

services:
  spa:
    container_name: react-spa
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    build:
      context: ./src/spa
      dockerfile: Dockerfile
    restart: always
    networks:
      - triptime