version: '3'

services:
  spa:
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./src/spa:/usr/app/:delegated
      - ./src/spa/node_modules:/usr/app/node_modules:delegated
      - /usr/app/.next
    command: npm run dev
  api:
    ports:
      - "3000:80"
